server:
  port: 9095
dir:
  qrcode: /workspace/imagens
spring:
  rabbitmq:
    #host: localhost
    host: 172.19.0.2
  data:
    mongodb:
      authentication-database: qrcode
      host: 192.168.1.200
      port: 27017
      username: admin
      password: admin
      database: qrcode
      show-sql: true
  activemq:
    packages:
      trust-all:
integration:
  produto:
    url: http://172.19.0.4:9094
    #url: localhost:9092
  parceiro:
    url: http://172.19.0.3:9093
    #url: localhost:9093
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

